### ISSUE TITLE
Mark homework 1, exercise 1_2 Carson-Hoffman

### ISSUE THREAD

**Issue by cahoffman** [cahoffman/statWORK679#1]
https://github.com/cahoffman/statWORK679/commit/d17e995e9da698d39f2ca20251fdee18b09258b0
@cecileane
I completed the exercise 1 and 2 for hw1. For part on it change the names of the files in the log and out directory. To run it go into the log or out folder then run the script. For question 2 run the shell cript from the parent folder of log and out. This will create a .csv file analysis-p2-hw1.csv data is in that file. Both functions will run successfully on the original data provided.

**Comment by cecileane** [comment]
Hi Carson,

Nice work! You have a clever use of `tail` with the `-c` option to get certain characters (knowing how many you needed). Some feedback below.

Small thing: your readme file (in `hw1/`) has very useful information. You could make it look nicer by using more of the markdown style, like backticks around code or file names.

Unfortunately your summarizing script sent errors at me. I got this sort of output (below). It did produce the summary table, but it was lacking the CPU time values:

```
$ ls
log         out
$ bash ../summarizeSNaQres.sh
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
    [-e pattern] [-f file] [--binary-files=value] [--color=when]
    [--context[=num]] [--directories=action] [--label] [--line-buffered]
    [--null] [pattern] [file ...]
( ... same thing repeated ~16 times... )
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
    [-e pattern] [-f file] [--binary-files=value] [--color=when]
    [--context[=num]] [--directories=action] [--label] [--line-buffered]
    [--null] [pattern] [file ...]
$ ls
analysis-p2-hw1.csv log         out
$ head -n 3 analysis-p2-hw1.csv
analysis:bT1, h:0, CPUtime: in seconds
analysis:net1_snaq, h:1, CPUtime: in seconds
analysis:newtry1, h:1, CPUtime: in seconds
```

Did you not submit the final version of your script? Are you using git with the command line to synchronize your folder exactly with your github repository?

Another issue is that when I ran the script again, the result file kept growing: the same output was repeated 3 times after I had run the script 3 times.

Finally, the csv file should just list the values on each line, not "analysis:" or "h:" or "CPUtime:". These names should appear in a header to explain what the numbers represent in each column. But I could see that your script picked up the values alone, and so it's just your final "echo" line that is printing too much.

One last thing: you didn't pick up all the digits after the decimal point for the CPU time. You should have used `'\d+\.\d+'` instead of `'\d+\.\d'` in your last grep (extra `+` near the end). Yes, that was missing from the example I had in the notes.

You learned a lot about parameter substitution! Unfortunately, you did not get much practice with `grep` as a result, or with _extended_ regular expressions. These are very useful for all other languages, not just the shell.

Please close this issue, or [assign](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) it to me and I can close it.

**Comment by cahoffman** [comment]
That is weird the CPU times did not show up I reran the code and it worked fine for me. Thanks for the useful information and comments. I will make the changes and try to implement more grep and sed on the  third part of hw1.

**Comment by cecileane** [comment]
it might have been due to a difference between GNU and BSD `grep`. I can't recall if I looked into this as a possible reason (for why it worked for you and not for me).
