### ISSUE TITLE
Mark homework 1, exercise 3 Carson-Hoffman 

### ISSUE THREAD

**Issue by cahoffman** [cahoffman/statWORK679#2]
@cecileane
https://github.com/cahoffman/statWORK679/commit/e3812ea2d44b878c7aacabf182d8e9a7d70de44b

Hello I submitted the hw 1.3 section the analysis file for P3 is also submitted on git hub but was not in the most recent commit. If you need anything else from me please let me know. Thanks for the great course. 

-Carson

**Comment by cecileane** [comment]
Thanks Carson! This is my way of asking Guanyu (@guanyunie) and Jialu (@njlfly) to try your script and provide feedback on it.

**Comment by JialuChenChina** [comment]
Hello Carson,
I cloned your stat679work repository in my computer and got some feedback for you. 
I like your documentation.  I found your `readme.md` in `hw1` is a very good introduction for your work. It helps me to understand how your works done. Besides the comments in your script are also very informative. 
As for the script part, since it always got some problems with`sed` in my machine (`sed: 1: "/ftolAbs=/{s/.*ftolAbs= ...": extra characters at the end of p command`), there are several columns I could not get. But besides that, the script works good and looks clean.
There's one thing I think might be improved. I found that all your files are in the root directory. I think it's better to build your directory structure with separate subdirectories for`results`,`script`,etc like the professor suggested. Although it may seem to be troublesome at first, it makes things easier to understand. 
About the `sed` part, I could not figure out why and it seems it works well in your computer. Maybe we could figure it out later.
Overall, I think your work is great.

**Comment by guanyunie** [comment]
Hi Carson,

Thanks for sharing your work. There are some problems to reproduce your result on my machine. I haven't used `GNU` before, so when I first run your code on my computer, it shows this:

``` shell
GuanyudeMacBook-Pro:hw1 guanyunie$ bash summarizeSNaQres.sh 
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
    [-e pattern] [-f file] [--binary-files=value] [--color=when]
    [--context[=num]] [--directories=action] [--label] [--line-buffered]
    [--null] [pattern] [file ...]
sed: 1: "/ftolAbs=/{s/.*ftolAbs= ...": extra characters at the end of p command
sed: 1: "/ftolRel=/{s/.*ftolRel= ...": extra characters at the end of p command
sed: 1: "/xtolAbs=/{s/.*xtolAbs= ...": extra characters at the end of p command
sed: 1: "/xtolRel=/{s/.*xtolRel= ...": extra characters at the end of p command
summarizeSNaQres.sh: line 39: -1: substring expression < 0
```

It is good to use `GNU`, but I think you should adding comments on what is not normal in your code(I assume we didn't practice `GNU` much in class).

After I installed `GNU`, there is still one small problem. Here is what I got:

``` shell
GuanyudeMacBook-Pro:hw1 guanyunie$ bash summarizeSNaQres.sh 
summarizeSNaQres.sh: line 39: -1: substring expression < 0
```

So I looked into your **line 39**, you used

``` shell
xrel=${xrel::-1}
```

to remove the . at the end. To see what is returned before this step, I added 

``` shell
echo $xrel
```

in front of 

``` shell
xrel=${xrel::-1}
```

and the result:

``` shell
GuanyudeMacBook-Pro:hw1 guanyunie$ bash summarizeSNaQres.sh 
0.001.
summarizeSNaQres.sh: line 40:  -1: substring expression < 0
```

which implies that there are problems right in this step, and I cannot figure out why. I think you should try using `sed` to substitute the last **.** by **empty string**. 

Another thing, all your works are in the root directory, which I think can be improved by separate them into `results` file, `scripts` file, `data` file, etc. 

Thanks for sharing your work!

Best,
Guanyu Nie

**Comment by cecileane** [comment]
So it looks like Jialu's problem was the same as Guanyu's: caused by having BSD utilities and not GNU utilities. It's great practice to document assumptions: here to say somewhere in a readme file or inside the script, that GNU `grep` or GNU `sed` is assumed. Such comments help collaborators and users a great deal, to help them fix "bugs".
