### ISSUE TITLE
Mark homework 2, exercise 1 Carson-Hoffman

### ISSUE THREAD

**Issue by cahoffman** [cahoffman/statWORK679#3]
@cecileane
https://github.com/cahoffman/statWORK679/commit/2409703012b010d4ccb05d1080dc701dbe3305a0

I have uploaded my completed hw2 for the stats class. Three files are uploaded. 1) the .py file which is used to create the merged .csv document. 2) readme.md file explaining what is in my folders. 3) test.csv which is the output merged file from using my function.

**Comment by cecileane** [comment]
Hi Carson,

Very nice job! and your script worked for me. More details below.

## overall presentation

Your readme file has great information: very clear intructions on what to do and what to expect. It's really great that you indicated which version of Python you used to develop your test. You could have made more use of markdown style. For instance, you wrote this to show what running your script will look like:

    "Enter Energy Filename: "
    "Enter Temperature Filename: "
    "Do you want to append to a file? (yes/no)  "
    "Please enter appended file name:" or "Please enter new file name:"

and then this:

    Enter Energy Filename:energy.csv
    Enter Temperature Filename:waterTemperature.csv
    Do you want to append to a file? (yes/no)  no
    Please enter new file name:NewOut.csv

But with markdown style, these 4 lines appear one after the other without newlines, see [here](https://github.com/cahoffman/statWORK679/blob/master/hw2/readme.md).
To make good use of markdown style and make your section appear nicer, you have 2 options: either indent your text with 4 spaces to make it a quoted block. That's what I did above. The other option would have been to finish each line with 2 spaces. With markdown, 2 spaces at the end of the line mean to force a newline. I'll do it below, not quoted, but the text does use 4 lines:

Enter Energy Filename:energy.csv  
Enter Temperature Filename:waterTemperature.csv  
Do you want to append to a file? (yes/no)  no  
Please enter new file name:NewOut.csv  


## running your script

I found that your script always appended to the output file, even when I answered "no" to the 3rd question. When I answered "yes", the header line was not printed (which was perfect). When I answered "no", the header line and the data were all appended to the file. Other than this, the output was great. A few energy values were rounded:

    38,07/30/16 11:26:34 PM,85.87,12.06
    ...
    158,08/04/16 11:26:34 PM,84.81,11.64
    ...
    182,08/05/16 11:26:34 PM,82.87,10.48

I expected this instead:

    38,07/30/16 11:26:34 PM,85.87,12.062
    ...
    158,08/04/16 11:26:34 PM,84.81,11.646
    ...
    182,08/05/16 11:26:34 PM,82.87,10.482

This rounding occurred for kWh values above 10: for which 2 digits were retains after the decimal points instead of 3. Probably a result of using numpy. By the way, instructions asked not to use "pre-defined modules for handling data arrays or merging data files", so numpy was not recommended given the learning goals for this exercise...

## about your code

I like that you have documentation (with a docstring) for your module.

On lines 18-19, the last row of the energy data is deleted, but it would have been best to first check that this line contained "Total", to check your assumption --and return a warning at least if the row did not have "Total".

You used a bunch of different tools from numpy, good learning! Nice use of the time module too.

I found that you could have chosen better variable names. On lines 38-39 for instance, you have this:

```python
N = len(energyval) # number of energy values for energy file
AddToArray = numpy.chararray((len(timevals), 1),itemsize=5)
```

On these lines it's clear that `N` is the number of energy values, but later when you use `N`, we don't remember what it is, so it makes is hard to understand your code. A better name for `N` would have been something like `numEnergy` or `numE` for instance. The name `AddToArray` is not explicit at all. You don't have any comment either to explain what this object will contain.

The appending instead of overwriting occurs on lines 61, 63, 67.
Finally, it would have been best to define functions, instead of having all in one straight chunk.

You have a smart use of `a` initialized at 0 then re-initialized back to `-1` to treat the first energy value differently from the others. I like it. You should have had a comment to explain this in your code, it's an important point!

You can go ahead and close this issue now.

**Comment by cahoffman** [comment]
Thanks for all the great comments.
